# -*- coding: utf-8 -*-
{
    "name": "Hospital Management",
    "summary": "Hospital Management system",
    "description": """Hospital Management system""",
    "author": "Dung Vo Truong",
    "website": "www.myhospital.com",
    "version": "0.1",
    "depends": ["mail"],
    "data": [
        # "security/ir.model.access.csv",
        "views/patient_view.xml",
        "views/female_patient_view.xml",
        "views/appointment_view.xml",
        "views/menu.xml",
        "reports/patient_card.xml",
        "reports/report.xml",
    ],
    "demo": [],
    "sequence": -100,
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
